# Generated by Django 4.2.7 on 2026-02-09 09:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_email_alter_user_first_name_and_more'),
        ('accounts', '0002_user_device_session_id'),
    ]

    operations = [
    ]
