# Generated by Django 4.2.11 on 2026-02-10 08:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_add_indexes'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='otpcode',
            new_name='accounts_ot_user_id_0b8326_idx',
            old_name='accounts_otp_user_compound_idx',
        ),
        migrations.RenameIndex(
            model_name='user',
            new_name='accounts_us_is_acti_a5841d_idx',
            old_name='accounts_user_is_active_idx',
        ),
        migrations.RenameIndex(
            model_name='user',
            new_name='accounts_us_phone_f54457_idx',
            old_name='accounts_user_phone_idx',
        ),
        migrations.RenameIndex(
            model_name='user',
            new_name='accounts_us_device__62edf1_idx',
            old_name='accounts_device_session_idx',
        ),
    ]
