# Generated by Django 4.2.11 on 2026-02-11 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_rename_accounts_otp_user_compound_idx_accounts_ot_user_id_0b8326_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True),
        ),
    ]
