# Generated by Django 4.2.11 on 2026-02-12 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_alter_vehicle_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='fcm_device_token',
            field=models.CharField(blank=True, help_text='Firebase Cloud Messaging device token for push notifications', max_length=255, null=True, verbose_name='FCM Device Token'),
        ),
        migrations.AddField(
            model_name='user',
            name='fcm_token_updated_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='FCM Token Updated At'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['fcm_device_token'], name='accounts_us_fcm_dev_7f69cb_idx'),
        ),
    ]
