# Generated by Django 4.2.11 on 2026-02-12 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0011_alter_parkingsession_actual_end_time_and_more'),
        ('accounts', '0009_user_fcm_device_token_user_fcm_token_updated_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='assigned_zones',
            field=models.ManyToManyField(blank=True, help_text='Zones assigned to this officer for monitoring', related_name='assigned_officers', to='parking.zone', verbose_name='Assigned Zones'),
        ),
    ]
