# Generated by Django 4.2.11 on 2026-02-12 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_user_assigned_zones'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='user',
            name='accounts_us_device__62edf1_idx',
        ),
        migrations.RemoveField(
            model_name='user',
            name='device_session_id',
        ),
        migrations.AddField(
            model_name='user',
            name='current_device_id',
            field=models.CharField(blank=True, help_text='Unique identifier of the currently logged-in device', max_length=255, null=True, verbose_name='Current Device ID'),
        ),
        migrations.AddField(
            model_name='user',
            name='current_session_token',
            field=models.CharField(blank=True, help_text='JWT token ID (jti) of active session', max_length=500, null=True, verbose_name='Current Session Token'),
        ),
        migrations.AddField(
            model_name='user',
            name='last_login_device',
            field=models.CharField(blank=True, help_text='Device info for logging purposes', max_length=255, null=True, verbose_name='Last Login Device'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['current_session_token'], name='accounts_us_current_ac916b_idx'),
        ),
    ]
