# Generated by Django 4.2.11 on 2026-02-13 06:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0004_country'),
        ('accounts', '0011_remove_user_accounts_us_device__62edf1_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='common.country', verbose_name='Country'),
        ),
    ]
