# Generated by Django 4.2.7 on 2026-02-13 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_user_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='can_receive_chats',
            field=models.BooleanField(default=False, help_text='Whether this officer/agent is available to receive chat assignments', verbose_name='Can Receive Chats'),
        ),
    ]
