# Generated by Django 4.2.7 on 2026-02-14 14:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_user_acc_usr_role_idx_user_acc_usr_cntry_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserLocation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('is_driver_app', models.BooleanField(default=True, help_text='True if sent from driver app, False if officer app')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='location_history', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['user', '-timestamp'], name='accounts_us_user_id_dc4415_idx'), models.Index(fields=['latitude', 'longitude'], name='accounts_us_latitud_2e7683_idx'), models.Index(fields=['timestamp'], name='accounts_us_timesta_c18bbb_idx')],
            },
        ),
    ]
