# Generated by Django 4.2.7 on 2026-02-17 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_userlocation'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='deletion_planned_at',
            field=models.DateTimeField(blank=True, help_text='Scheduled date for permanent deletion', null=True, verbose_name='Deletion Planned At'),
        ),
        migrations.AddField(
            model_name='user',
            name='deletion_requested_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Deletion Requested At'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['deletion_planned_at'], name='acc_usr_del_plan_idx'),
        ),
    ]
