# Generated by Django 4.2.23 on 2026-02-28 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_user_deletion_planned_at_user_deletion_requested_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='fcm_device_token',
            field=models.TextField(blank=True, help_text='Firebase Cloud Messaging device token for push notifications', null=True, verbose_name='FCM Device Token'),
        ),
    ]
