# Generated by Django 4.2.7 on 2026-03-07 08:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0006_countryconfig'),
        ('accounts', '0017_alter_user_fcm_device_token'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='wallet_balance',
        ),
        migrations.AddField(
            model_name='user',
            name='wallet_balance_legacy',
            field=models.DecimalField(db_column='wallet_balance', decimal_places=2, default=0.0, max_digits=12, verbose_name='Legacy Wallet Balance'),
        ),
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('balance', models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='Balance')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wallets', to='common.country')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wallets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Wallet',
                'verbose_name_plural': 'Wallets',
                'unique_together': {('user', 'country')},
            },
        ),
    ]
