# Generated by Django 4.2.7 on 2026-03-15 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0018_remove_user_wallet_balance_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('driver', 'Driver'), ('officer', 'Officer'), ('admin', 'Admin'), ('zone_owner', 'Zone Owner')], default='driver', max_length=20, verbose_name='Role'),
        ),
    ]
