# Generated by Django 4.2.7 on 2026-03-25 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0019_add_zone_owner_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='app_version',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='App Version'),
        ),
        migrations.AddField(
            model_name='user',
            name='device_model',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Device Model'),
        ),
        migrations.AddField(
            model_name='user',
            name='device_os',
            field=models.CharField(blank=True, choices=[('android', 'Android'), ('ios', 'iOS')], max_length=20, null=True, verbose_name='Device OS'),
        ),
    ]
