# Generated by Django 4.2.7 on 2026-09-26 19:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0010_country_latitude_country_longitude_and_more'),
        ('accounts', '0020_user_app_version_user_device_model_user_device_os'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallet',
            name='country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_related', to='common.country'),
        ),
    ]
