# Generated by Django 4.2.7 on 2026-02-05 07:50

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParkingSlot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('slot_code', models.CharField(max_length=10)),
                ('status', models.CharField(choices=[('available', 'Available'), ('occupied', 'Occupied'), ('reserved', 'Reserved'), ('disabled', 'Disabled')], default='available', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Zone',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('hourly_rate', models.DecimalField(decimal_places=2, max_digits=8)),
                ('max_duration_hours', models.IntegerField(default=24)),
                ('is_active', models.BooleanField(default=True)),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('radius_meters', models.IntegerField(default=100)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reserved_from', models.DateTimeField()),
                ('reserved_until', models.DateTimeField()),
                ('cost', models.DecimalField(decimal_places=2, max_digits=8)),
                ('is_active', models.BooleanField(default=True)),
                ('parking_slot', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='parking.parkingslot')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='accounts.vehicle')),
                ('zone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='parking.zone')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='parkingslot',
            name='zone',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slots', to='parking.zone'),
        ),
        migrations.CreateModel(
            name='ParkingSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('start_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('planned_end_time', models.DateTimeField()),
                ('actual_end_time', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('completed', 'Completed'), ('expired', 'Expired'), ('cancelled', 'Cancelled')], default='active', max_length=20)),
                ('estimated_cost', models.DecimalField(decimal_places=2, max_digits=8)),
                ('final_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('parking_slot', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='parking.parkingslot')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parking_sessions', to='accounts.vehicle')),
                ('zone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='parking.zone')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='parkingslot',
            unique_together={('zone', 'slot_code')},
        ),
        migrations.AddConstraint(
            model_name='parkingsession',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'active')), fields=('vehicle',), name='one_active_session_per_vehicle'),
        ),
    ]
