# Generated by Django 4.2.7 on 2026-02-05 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='parkingslot',
            name='diagram_height',
            field=models.IntegerField(default=80, help_text='Slot height on diagram'),
        ),
        migrations.AddField(
            model_name='parkingslot',
            name='diagram_width',
            field=models.IntegerField(default=40, help_text='Slot width on diagram'),
        ),
        migrations.AddField(
            model_name='parkingslot',
            name='diagram_x',
            field=models.IntegerField(default=0, help_text='X position on diagram'),
        ),
        migrations.AddField(
            model_name='parkingslot',
            name='diagram_y',
            field=models.IntegerField(default=0, help_text='Y position on diagram'),
        ),
        migrations.AddField(
            model_name='parkingslot',
            name='slot_type',
            field=models.CharField(choices=[('regular', 'Regular'), ('disabled', 'Disabled'), ('electric', 'Electric Vehicle'), ('compact', 'Compact'), ('motorcycle', 'Motorcycle')], default='regular', max_length=20),
        ),
        migrations.AddField(
            model_name='zone',
            name='diagram_height',
            field=models.IntegerField(default=600, help_text='Diagram height in pixels'),
        ),
        migrations.AddField(
            model_name='zone',
            name='diagram_image',
            field=models.ImageField(blank=True, help_text='Parking layout diagram (like airplane seat map)', null=True, upload_to='zones/diagrams/'),
        ),
        migrations.AddField(
            model_name='zone',
            name='diagram_width',
            field=models.IntegerField(default=800, help_text='Diagram width in pixels'),
        ),
        migrations.AddField(
            model_name='zone',
            name='zone_image',
            field=models.ImageField(blank=True, help_text='Photo of the actual parking zone', null=True, upload_to='zones/images/'),
        ),
    ]
