# Generated by Django 4.2.7 on 2026-02-05 11:28

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0002_parkingslot_diagram_height_parkingslot_diagram_width_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='parkingslot',
            name='diagram_rotation',
            field=models.IntegerField(default=0, help_text='Rotation angle in degrees'),
        ),
        migrations.CreateModel(
            name='ZoneEntrance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=50)),
                ('diagram_x', models.IntegerField()),
                ('diagram_y', models.IntegerField()),
                ('width', models.IntegerField(default=60)),
                ('height', models.IntegerField(default=20)),
                ('entrance_type', models.CharField(choices=[('entry', 'Entry Only'), ('exit', 'Exit Only'), ('both', 'Entry/Exit')], default='both', max_length=20)),
                ('zone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entrances', to='parking.zone')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ZoneBoundary',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=50)),
                ('points', models.JSONField(help_text='Array of {x, y} coordinates defining the boundary')),
                ('boundary_type', models.CharField(choices=[('outer', 'Outer Boundary'), ('inner', 'Inner Boundary'), ('restricted', 'Restricted Area')], default='outer', max_length=20)),
                ('color', models.CharField(default='#007bff', max_length=7)),
                ('zone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='boundaries', to='parking.zone')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DrivePath',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=50)),
                ('points', models.JSONField(help_text='Array of {x, y} coordinates defining the path')),
                ('width', models.IntegerField(default=30, help_text='Path width in pixels')),
                ('path_type', models.CharField(choices=[('main', 'Main Drive'), ('lane', 'Parking Lane'), ('oneway', 'One Way')], default='main', max_length=20)),
                ('color', models.CharField(default='#6c757d', max_length=7)),
                ('zone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='drive_paths', to='parking.zone')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
