# Generated by Django 4.2.11 on 2026-02-05 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0003_parkingslot_diagram_rotation_zoneentrance_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='zone',
            name='total_slots',
            field=models.IntegerField(default=0, help_text='Total number of parking slots in this zone'),
        ),
    ]
