# Generated by Django 4.2.7 on 2026-02-09 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0004_zone_total_slots'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parkingsession',
            name='estimated_cost',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.AlterField(
            model_name='parkingsession',
            name='final_cost',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='cost',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.AlterField(
            model_name='zone',
            name='hourly_rate',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
    ]
