# Generated by Django 4.2.11 on 2026-02-10 08:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0006_add_parkingsession_indexes'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='parkingsession',
            new_name='parking_par_vehicle_a87999_idx',
            old_name='parking_session_vehicle_status_idx',
        ),
        migrations.RenameIndex(
            model_name='parkingsession',
            new_name='parking_par_status_3b9c68_idx',
            old_name='parking_session_status_time_idx',
        ),
        migrations.RenameIndex(
            model_name='parkingsession',
            new_name='parking_par_zone_id_a36020_idx',
            old_name='parking_session_zone_status_idx',
        ),
    ]
