# Generated by Django 4.2.7 on 2026-02-11 10:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0007_rename_parking_session_vehicle_status_idx_parking_par_vehicle_a87999_idx_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='zone',
            options={'ordering': ['name']},
        ),
    ]
