# Generated by Django 4.2.11 on 2026-02-11 16:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0009_add_expiry_and_slot_indexes'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='parkingsession',
            name='parkingsession_status_planned_idx',
        ),
        migrations.RemoveIndex(
            model_name='parkingslot',
            name='parkingslot_zone_status_idx',
        ),
    ]
