# Generated by Django 4.2.11 on 2026-02-11 16:53

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0010_remove_parkingsession_parkingsession_status_planned_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parkingsession',
            name='actual_end_time',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='parkingsession',
            name='start_time',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='parkingslot',
            name='slot_type',
            field=models.CharField(choices=[('regular', 'Regular'), ('disabled', 'Disabled'), ('electric', 'Electric Vehicle'), ('compact', 'Compact'), ('motorcycle', 'Motorcycle')], db_index=True, default='regular', max_length=20),
        ),
        migrations.AlterField(
            model_name='parkingslot',
            name='status',
            field=models.CharField(choices=[('available', 'Available'), ('occupied', 'Occupied'), ('reserved', 'Reserved'), ('disabled', 'Disabled')], db_index=True, default='available', max_length=20),
        ),
        migrations.AlterField(
            model_name='zone',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True),
        ),
    ]
