# Generated by Django 4.2.11 on 2026-02-12 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0011_alter_parkingsession_actual_end_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='zone',
            name='code',
            field=models.CharField(blank=True, help_text='Short unique code for the zone (e.g. JB01)', max_length=20, null=True, unique=True),
        ),
    ]
