# Generated by Django 4.2.11 on 2026-02-13 06:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0004_country'),
        ('parking', '0012_zone_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='zone',
            name='country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='zones', to='common.country'),
        ),
    ]
