# Generated by Django 4.2.11 on 2026-02-13 06:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0004_country'),
        ('parking', '0013_zone_country'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zone',
            name='country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_related', to='common.country'),
        ),
    ]
