# Generated by Django 4.2.11 on 2026-02-13 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0014_alter_zone_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='payment_reference',
            field=models.CharField(blank=True, help_text='Payment transaction reference', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='reservation',
            name='status',
            field=models.CharField(choices=[('pending_payment', 'Pending Payment'), ('confirmed', 'Confirmed'), ('cancelled', 'Cancelled'), ('completed', 'Completed'), ('expired', 'Expired')], db_index=True, default='pending_payment', max_length=20),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='reserved_from',
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='reserved_until',
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AddIndex(
            model_name='reservation',
            index=models.Index(fields=['zone', 'status', 'reserved_from', 'reserved_until'], name='parking_res_zone_id_14e45a_idx'),
        ),
        migrations.AddIndex(
            model_name='reservation',
            index=models.Index(fields=['vehicle', 'status'], name='parking_res_vehicle_8adb40_idx'),
        ),
    ]
