# Generated by Django 4.2.11 on 2026-02-13 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0015_reservation_payment_reference_reservation_status_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='parkingsession',
            index=models.Index(fields=['vehicle'], name='prk_sess_veh_idx'),
        ),
        migrations.AddIndex(
            model_name='parkingsession',
            index=models.Index(fields=['actual_end_time'], name='prk_sess_end_idx'),
        ),
        migrations.AddIndex(
            model_name='parkingsession',
            index=models.Index(fields=['created_at'], name='prk_sess_created_idx'),
        ),
        migrations.AddIndex(
            model_name='parkingsession',
            index=models.Index(fields=['start_time', 'status'], name='prk_sess_start_stat_idx'),
        ),
        migrations.AddIndex(
            model_name='parkingslot',
            index=models.Index(fields=['zone'], name='prk_slot_zone_idx'),
        ),
        migrations.AddIndex(
            model_name='parkingslot',
            index=models.Index(fields=['zone', 'status'], name='prk_slot_z_stat_idx'),
        ),
        migrations.AddIndex(
            model_name='parkingslot',
            index=models.Index(fields=['slot_type'], name='prk_slot_type_idx'),
        ),
        migrations.AddIndex(
            model_name='parkingslot',
            index=models.Index(fields=['zone', 'slot_type', 'status'], name='prk_slot_z_t_s_idx'),
        ),
        migrations.AddIndex(
            model_name='reservation',
            index=models.Index(fields=['reserved_from'], name='prk_res_from_idx'),
        ),
        migrations.AddIndex(
            model_name='reservation',
            index=models.Index(fields=['reserved_until'], name='prk_res_until_idx'),
        ),
        migrations.AddIndex(
            model_name='reservation',
            index=models.Index(fields=['created_at'], name='prk_res_created_idx'),
        ),
        migrations.AddIndex(
            model_name='zone',
            index=models.Index(fields=['country'], name='prk_zone_cntry_idx'),
        ),
        migrations.AddIndex(
            model_name='zone',
            index=models.Index(fields=['created_at'], name='prk_zone_created_idx'),
        ),
        migrations.AddIndex(
            model_name='zone',
            index=models.Index(fields=['code'], name='prk_zone_code_idx'),
        ),
        migrations.AddIndex(
            model_name='zone',
            index=models.Index(fields=['is_active', 'country'], name='prk_zone_act_cnt_idx'),
        ),
    ]
