# Generated by Django 4.2.7 on 2026-02-16 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0016_parkingsession_prk_sess_veh_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parkingsession',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('completed', 'Completed'), ('expired', 'Expired'), ('cancelled', 'Cancelled'), ('pending_payment', 'Pending Payment')], default='active', max_length=20),
        ),
    ]
