# Generated by Django 4.2.7 on 2026-03-14 08:04

from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0007_systemconfiguration_default_hourly_rate_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('parking', '0018_parkingsession_country'),
    ]

    operations = [
        migrations.CreateModel(
            name='ZoneApplication',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('proposed_name', models.CharField(max_length=100)),
                ('address', models.TextField()),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('total_slots', models.IntegerField(default=1)),
                ('proposed_hourly_rate', models.DecimalField(decimal_places=2, max_digits=12)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('documents', models.FileField(blank=True, help_text='Proof of ownership or ID', null=True, upload_to='zone_applications/docs/')),
                ('admin_notes', models.TextField(blank=True, help_text='Internal notes by admins')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='zone',
            name='commission_rate',
            field=models.DecimalField(decimal_places=2, default=Decimal('10.00'), help_text='Company commission percentage (e.g., 10 for 10%)', max_digits=5),
        ),
        migrations.AddField(
            model_name='zone',
            name='owner',
            field=models.ForeignKey(blank=True, help_text='Owner for private parking zones', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_zones', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='zone',
            name='zone_type',
            field=models.CharField(choices=[('company', 'Company'), ('private', 'Private')], default='company', max_length=20),
        ),
        migrations.AlterField(
            model_name='parkingsession',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('completed', 'Completed'), ('expired', 'Expired'), ('cancelled', 'Cancelled'), ('pending_payment', 'Pending Payment')], db_index=True, default='active', max_length=20),
        ),
        migrations.AddIndex(
            model_name='parkingsession',
            index=models.Index(fields=['status', 'planned_end_time'], name='prk_sess_stat_end_idx'),
        ),
        migrations.AddIndex(
            model_name='parkingsession',
            index=models.Index(fields=['planned_end_time'], name='prk_sess_plan_end_idx'),
        ),
        migrations.AddField(
            model_name='zoneapplication',
            name='country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_related', to='common.country'),
        ),
        migrations.AddField(
            model_name='zoneapplication',
            name='created_zone',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='application', to='parking.zone'),
        ),
        migrations.AddField(
            model_name='zoneapplication',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='zone_applications', to=settings.AUTH_USER_MODEL),
        ),
    ]
