# Generated by Django 4.2.17 on 2026-03-14 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0019_zoneapplication_zone_commission_rate_zone_owner_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='zoneapplication',
            name='access_instructions',
            field=models.TextField(blank=True, help_text='Specific directions on how to find or enter the space'),
        ),
        migrations.AddField(
            model_name='zoneapplication',
            name='has_cctv',
            field=models.BooleanField(default=False, help_text='Are there CCTV cameras covering the area?'),
        ),
        migrations.AddField(
            model_name='zoneapplication',
            name='has_security',
            field=models.BooleanField(default=False, help_text='Is there a physical security guard?'),
        ),
        migrations.AddField(
            model_name='zoneapplication',
            name='operating_hours',
            field=models.CharField(default='24/7', help_text='E.g., 24/7, 8 AM - 6 PM, Weekends only', max_length=100),
        ),
        migrations.AddField(
            model_name='zoneapplication',
            name='parking_surface',
            field=models.CharField(choices=[('paved', 'Paved/Concrete'), ('gravel', 'Gravel/Dirt'), ('indoor', 'Indoor/Garage')], default='paved', max_length=50),
        ),
    ]
