# Generated by Django 4.2.7 on 2026-03-25 12:07

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0020_zoneapplication_access_instructions_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='service_fee',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Non-refundable service fee (5%)', max_digits=12),
        ),
        migrations.AddField(
            model_name='zone',
            name='supports_dynamic_pricing',
            field=models.BooleanField(default=False, help_text='Toggle dynamic pricing for this zone'),
        ),
        migrations.AddField(
            model_name='zone',
            name='supports_reservations',
            field=models.BooleanField(default=True, help_text='Toggle if this zone supports reservations'),
        ),
    ]
