# Generated by Django 4.2.7 on 2026-03-25 12:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0020_user_app_version_user_device_model_user_device_os'),
        ('parking', '0021_reservation_service_fee_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='parkingsession',
            name='one_active_session_per_vehicle',
        ),
        migrations.AddField(
            model_name='parkingsession',
            name='guest_license_plate',
            field=models.CharField(blank=True, help_text='Plate number for non-app users', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='parkingsession',
            name='vehicle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='parking_sessions', to='accounts.vehicle'),
        ),
        migrations.AddConstraint(
            model_name='parkingsession',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'active'), ('vehicle__isnull', False)), fields=('vehicle',), name='one_active_session_per_vehicle'),
        ),
        migrations.AddConstraint(
            model_name='parkingsession',
            constraint=models.UniqueConstraint(condition=models.Q(('guest_license_plate__isnull', False), ('status', 'active')), fields=('guest_license_plate',), name='one_active_session_per_guest'),
        ),
    ]
