# Generated by Django 4.2.7 on 2026-03-31 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0022_remove_parkingsession_one_active_session_per_vehicle_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='zoneapplication',
            name='zone_picture',
            field=models.ImageField(blank=True, help_text='Photo of the actual parking zone', null=True, upload_to='zone_applications/pics/'),
        ),
    ]
