# Generated by Django 4.2.7 on 2026-09-26 19:33

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0010_country_latitude_country_longitude_and_more'),
        ('parking', '0024_pricingrule'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='pricingrule',
            new_name='parking_pri_zone_id_7d2889_idx',
            old_name='parking_pric_zone_id_8b8b8b_idx',
        ),
        migrations.RenameIndex(
            model_name='pricingrule',
            new_name='parking_pri_zone_id_e4b43f_idx',
            old_name='parking_pric_zone_id_9c9c9c_idx',
        ),
        migrations.RemoveField(
            model_name='demandbasedpricingrule',
            name='price_multiplier',
        ),
        migrations.RemoveField(
            model_name='specialeventpricingrule',
            name='end_time',
        ),
        migrations.RemoveField(
            model_name='specialeventpricingrule',
            name='event_date',
        ),
        migrations.RemoveField(
            model_name='specialeventpricingrule',
            name='event_name',
        ),
        migrations.RemoveField(
            model_name='specialeventpricingrule',
            name='start_time',
        ),
        migrations.AddField(
            model_name='demandbasedpricingrule',
            name='comparison',
            field=models.CharField(choices=[('gte', 'Greater than or equal'), ('lte', 'Less than or equal')], default='gte', help_text='How to compare current occupancy with threshold', max_length=10),
        ),
        migrations.AddField(
            model_name='parkingsession',
            name='auto_extend_enabled',
            field=models.BooleanField(default=False, help_text='Allow automatic 1-hour extension if funds are available'),
        ),
        migrations.AddField(
            model_name='parkingsession',
            name='can_extend',
            field=models.BooleanField(default=True, help_text='Whether this session can be extended or is constrained by an upcoming reservation'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_related', to='common.country'),
        ),
        migrations.AddField(
            model_name='specialeventpricingrule',
            name='end_datetime',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='When this special pricing ends'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='specialeventpricingrule',
            name='start_datetime',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='When this special pricing starts'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='parkingsession',
            name='country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_related', to='common.country'),
        ),
        migrations.AlterField(
            model_name='pricingrule',
            name='country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_related', to='common.country'),
        ),
        migrations.AlterField(
            model_name='zone',
            name='country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_related', to='common.country'),
        ),
        migrations.AlterField(
            model_name='zoneapplication',
            name='country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_related', to='common.country'),
        ),
    ]
