from celery import shared_task
from django.utils import timezone
from datetime import timedelta
from django.db.models import Sum, Count
from django.core.mail import send_mail
from django.conf import settings
from django.contrib.auth import get_user_model
import logging

from apps.analytics.models import RevenueRecord
from apps.parking.models import Zone
from apps.enforcement.models import Violation, OfficerStatus

User = get_user_model()
logger = logging.getLogger(__name__)

@shared_task
def send_weekly_admin_report():
    """
    Generate and send a weekly summary report to system administrators.
    Runs early Monday morning (e.g., 08:00 AM).
    """
    today = timezone.now().date()
    start_date = today - timedelta(days=7)
    
    logger.info(f"Generating weekly report for period: {start_date} to {today}")
    
    # 1. Aggregate Weekly Revenue & Activity (from RevenueRecord)
    weekly_stats = RevenueRecord.objects.filter(
        date__gte=start_date,
        date__lt=today
    ).aggregate(
        total_revenue=Sum('total_revenue'),
        total_sessions=Sum('total_sessions'),
        total_violations=Sum('total_violations')
    )
    
    revenue = weekly_stats['total_revenue'] or 0
    sessions = weekly_stats['total_sessions'] or 0
    violations = weekly_stats['total_violations'] or 0
    
    # 2. New Users
    new_users = User.objects.filter(
        created_at__gte=start_date,
        created_at__lt=today
    ).count()
    
    # 3. Active Zones & Officers (Snapshot)
    active_zones = Zone.objects.filter(is_active=True).count()
    active_officers = User.objects.filter(role='officer', is_active=True).count()
    
    # 4. Construct Email Content
    subject = f"[Weekly Report] Jambo Park Metrics ({start_date} - {today})"
    
    html_message = f"""
    <html>
    <body>
        <h2>Weekly Performance Report</h2>
        <p>Period: <strong>{start_date}</strong> to <strong>{today}</strong></p>
        
        <table border="1" cellpadding="10" style="border-collapse: collapse;">
            <tr>
                <td><strong>Total Revenue</strong></td>
                <td>${revenue:,.2f}</td>
            </tr>
            <tr>
                <td><strong>Total Parking Sessions</strong></td>
                <td>{sessions:,}</td>
            </tr>
            <tr>
                <td><strong>Total Violations Issued</strong></td>
                <td>{violations:,}</td>
            </tr>
            <tr>
                <td><strong>New User Signups</strong></td>
                <td>{new_users:,}</td>
            </tr>
             <tr>
                <td><strong>Active Zones</strong></td>
                <td>{active_zones}</td>
            </tr>
             <tr>
                <td><strong>Active Officers</strong></td>
                <td>{active_officers}</td>
            </tr>
        </table>
        
        <p><em>This is an automated report generated by the Jambo Park autonomous system.</em></p>
    </body>
    </html>
    """
    
    # 5. Get Admin Emails
    admin_emails = list(User.objects.filter(is_superuser=True).values_list('email', flat=True))
    if not admin_emails:
        # Fallback to clear fallback if no superusers found
        admin_emails = [settings.DEFAULT_FROM_EMAIL]
        
    try:
        send_mail(
            subject=subject,
            message="Please view the HTML version of this email.",
            from_email=settings.DEFAULT_FROM_EMAIL,
            recipient_list=admin_emails,
            html_message=html_message,
            fail_silently=False,
        )
        logger.info(f"Weekly report sent to {len(admin_emails)} admins.")
        return f"Report sent to {len(admin_emails)} admins."
        
    except Exception as e:
        logger.error(f"Failed to send weekly report: {e}")
        return "Failed to send report."
