# Generated by Django 4.2.7 on 2026-02-09 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='pesapal_merchant_reference',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='pesapal_order_tracking_id',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
