# Generated by Django 4.2.11 on 2026-02-10 08:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0004_add_transaction_indexes'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='transaction',
            new_name='payments_tr_user_id_8d8d07_idx',
            old_name='payments_transaction_user_compound_idx',
        ),
        migrations.RenameIndex(
            model_name='transaction',
            new_name='payments_tr_status_e3597b_idx',
            old_name='payments_transaction_status_time_idx',
        ),
        migrations.RenameIndex(
            model_name='wallettransaction',
            new_name='payments_wa_user_id_10a461_idx',
            old_name='payments_wallet_user_type_idx',
        ),
        migrations.RenameIndex(
            model_name='wallettransaction',
            new_name='payments_wa_status_d9255e_idx',
            old_name='payments_wallet_status_time_idx',
        ),
    ]
