# Generated by Django 4.2.11 on 2026-02-13 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0005_rename_payments_transaction_user_compound_idx_payments_tr_user_id_8d8d07_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='wallettransaction',
            name='metadata',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
