# Generated by Django 4.2.7 on 2026-02-13 06:46

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0004_country'),
        ('payments', '0006_wallettransaction_metadata'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentGatewayConfig',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('gateway', models.CharField(choices=[('pesapal', 'Pesapal'), ('stripe', 'Stripe'), ('cash', 'Cash'), ('wallet', 'Wallet')], max_length=20)),
                ('name', models.CharField(help_text='Display name for the app', max_length=100)),
                ('credentials', models.JSONField(help_text='API keys, secrets, etc.')),
                ('is_sandbox', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True)),
                ('priority', models.PositiveIntegerField(default=0, help_text='Higher priority shows first')),
                ('country', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_related', to='common.country')),
            ],
            options={
                'ordering': ['-priority', 'name'],
                'unique_together': {('country', 'gateway')},
            },
        ),
    ]
