# Generated by Django 4.2.11 on 2026-02-13 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0007_paymentgatewayconfig'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['invoice_number'], name='pay_inv_num_idx'),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['transaction'], name='pay_inv_tx_idx'),
        ),
        migrations.AddIndex(
            model_name='paymentmethod',
            index=models.Index(fields=['user'], name='pay_meth_usr_idx'),
        ),
        migrations.AddIndex(
            model_name='paymentmethod',
            index=models.Index(fields=['is_active'], name='pay_meth_act_idx'),
        ),
        migrations.AddIndex(
            model_name='refund',
            index=models.Index(fields=['original_transaction'], name='pay_ref_tx_idx'),
        ),
        migrations.AddIndex(
            model_name='refund',
            index=models.Index(fields=['status'], name='pay_ref_stat_idx'),
        ),
        migrations.AddIndex(
            model_name='refund',
            index=models.Index(fields=['created_at'], name='pay_ref_created_idx'),
        ),
        migrations.AddIndex(
            model_name='wallettransaction',
            index=models.Index(fields=['user'], name='pay_wtx_u_idx'),
        ),
        migrations.AddIndex(
            model_name='wallettransaction',
            index=models.Index(fields=['transaction_type'], name='pay_wtx_tp_idx'),
        ),
        migrations.AddIndex(
            model_name='wallettransaction',
            index=models.Index(fields=['status'], name='pay_wtx_st_idx'),
        ),
        migrations.AddIndex(
            model_name='wallettransaction',
            index=models.Index(fields=['created_at'], name='pay_wtx_cr_idx'),
        ),
        migrations.AddIndex(
            model_name='wallettransaction',
            index=models.Index(fields=['user', 'created_at'], name='pay_wtx_u_cr_idx'),
        ),
    ]
