# Generated by Django 4.2.7 on 2026-03-14 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0009_refund_country_transaction_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentmethod',
            name='gateway',
            field=models.CharField(choices=[('pesapal', 'Pesapal'), ('stripe', 'Stripe'), ('cash', 'Cash'), ('wallet', 'Wallet')], default='stripe', max_length=20),
        ),
        migrations.AddField(
            model_name='paymentmethod',
            name='pesapal_token',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='charge_amount_processor',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='charge_currency_processor',
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='paymentmethod',
            name='stripe_payment_method_id',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='wallettransaction',
            name='transaction_type',
            field=models.CharField(choices=[('topup', 'Top-up'), ('payment', 'Parking Payment'), ('fine_payment', 'Fine Payment'), ('refund', 'Refund'), ('earning', 'Earning (Private Zone)'), ('withdrawal', 'Withdrawal')], max_length=20),
        ),
    ]
