# Generated by Django 4.2.17 on 2026-03-16 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0010_paymentmethod_gateway_paymentmethod_pesapal_token_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='wallettransaction',
            name='closing_balance',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='wallettransaction',
            name='opening_balance',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='wallettransaction',
            name='transaction_type',
            field=models.CharField(choices=[('topup', 'Top-up'), ('payment', 'Parking Payment'), ('fine_payment', 'Fine Payment'), ('refund', 'Refund'), ('earning', 'Earning (Private Zone)'), ('withdrawal', 'Withdrawal'), ('payout', 'Payout (Manual)')], max_length=20),
        ),
    ]
