# Generated by Django 4.2.7 on 2026-09-26 19:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0010_country_latitude_country_longitude_and_more'),
        ('payments', '0011_wallettransaction_closing_balance_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_related', to='common.country'),
        ),
        migrations.AddField(
            model_name='wallettransaction',
            name='country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_related', to='common.country'),
        ),
        migrations.AlterField(
            model_name='paymentgatewayconfig',
            name='country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_related', to='common.country'),
        ),
        migrations.AlterField(
            model_name='paymentgatewayconfig',
            name='gateway',
            field=models.CharField(choices=[('pesapal', 'Pesapal (cards, mobile money — Africa)'), ('stripe', 'Stripe'), ('paypal', 'PayPal'), ('mpesa', 'M-Pesa (Safaricom)'), ('flutterwave', 'Flutterwave'), ('paystack', 'Paystack'), ('razorpay', 'Razorpay'), ('cash', 'Cash (in-person)'), ('wallet', 'In-app wallet')], max_length=20),
        ),
        migrations.AlterField(
            model_name='paymentmethod',
            name='gateway',
            field=models.CharField(choices=[('pesapal', 'Pesapal (cards, mobile money — Africa)'), ('stripe', 'Stripe'), ('paypal', 'PayPal'), ('mpesa', 'M-Pesa (Safaricom)'), ('flutterwave', 'Flutterwave'), ('paystack', 'Paystack'), ('razorpay', 'Razorpay'), ('cash', 'Cash (in-person)'), ('wallet', 'In-app wallet')], default='stripe', max_length=20),
        ),
        migrations.AlterField(
            model_name='refund',
            name='country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_related', to='common.country'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_related', to='common.country'),
        ),
    ]
