# Generated by Django 4.2.7 on 2026-02-05 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SystemConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency', models.CharField(choices=[('USD', 'US Dollar ($)'), ('EUR', 'Euro (€)'), ('GBP', 'British Pound (£)'), ('CAD', 'Canadian Dollar (C$)'), ('AUD', 'Australian Dollar (A$)')], default='USD', max_length=3)),
                ('timezone', models.CharField(default='UTC', max_length=50)),
                ('company_name', models.CharField(default='Smart Parking System', max_length=100)),
                ('contact_email', models.EmailField(default='admin@smartparking.com', max_length=254)),
                ('contact_phone', models.CharField(default='+1234567890', max_length=20)),
            ],
            options={
                'verbose_name': 'System Configuration',
                'verbose_name_plural': 'System Configuration',
            },
        ),
    ]
