# Generated by Django 4.2.7 on 2026-02-09 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_alter_systemconfiguration_currency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='systemconfiguration',
            name='currency',
            field=models.CharField(choices=[('USD', 'US Dollar ($)'), ('EUR', 'Euro (€)'), ('GBP', 'British Pound (£)'), ('CAD', 'Canadian Dollar (C$)'), ('AUD', 'Australian Dollar (A$)'), ('UGX', 'Uganda Shilling (UGX)'), ('KES', 'Kenya Shilling (Ksh)'), ('GHS', 'Ghana Cedi (₵)')], default='UGX', max_length=3),
        ),
    ]
