# Generated by Django 4.2.11 on 2026-02-13 06:31

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0003_alter_systemconfiguration_currency'),
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('iso_code', models.CharField(help_text='ISO 3166-1 alpha-2 code (e.g. UG, KE)', max_length=2, unique=True)),
                ('currency', models.CharField(choices=[('USD', 'US Dollar ($)'), ('EUR', 'Euro (€)'), ('GBP', 'British Pound (£)'), ('CAD', 'Canadian Dollar (C$)'), ('AUD', 'Australian Dollar (A$)'), ('UGX', 'Uganda Shilling (UGX)'), ('KES', 'Kenya Shilling (Ksh)'), ('GHS', 'Ghana Cedi (₵)')], default='UGX', max_length=3)),
                ('currency_symbol', models.CharField(max_length=10)),
                ('timezone', models.CharField(default='Africa/Kampala', max_length=50)),
                ('phone_code', models.CharField(help_text='Dialing code (e.g. +256)', max_length=10)),
                ('flag_emoji', models.CharField(blank=True, max_length=10)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'Countries',
                'ordering': ['name'],
            },
        ),
    ]
