# Generated by Django 4.2.11 on 2026-02-13 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0004_country'),
    ]

    operations = [
        migrations.AlterField(
            model_name='country',
            name='currency',
            field=models.CharField(default='UGX', max_length=3),
        ),
    ]
