# Generated by Django 4.2.7 on 2026-02-16 15:28

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0005_alter_country_currency'),
    ]

    operations = [
        migrations.CreateModel(
            name='CountryConfig',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('payment_methods', models.JSONField(default=list, help_text="Available payment methods: ['wallet', 'pesapal', 'mpesa', 'flutterwave']")),
                ('exchange_rate_to_base', models.DecimalField(decimal_places=4, default=1.0, help_text="Exchange rate from base currency (UGX) to this country's currency", max_digits=10)),
                ('is_active', models.BooleanField(default=True)),
                ('country', models.OneToOneField(help_text='Country this configuration applies to', on_delete=django.db.models.deletion.CASCADE, related_name='payment_config', to='common.country')),
            ],
            options={
                'verbose_name': 'Country Payment Configuration',
                'verbose_name_plural': 'Country Payment Configurations',
            },
        ),
    ]
