# Generated by Django 4.2.17 on 2026-03-12 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0006_countryconfig'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemconfiguration',
            name='default_hourly_rate',
            field=models.DecimalField(decimal_places=2, default=2000.0, max_digits=12),
        ),
        migrations.AddField(
            model_name='systemconfiguration',
            name='grace_period_minutes',
            field=models.IntegerField(default=15),
        ),
        migrations.AddField(
            model_name='systemconfiguration',
            name='violation_fine_amount',
            field=models.DecimalField(decimal_places=2, default=50000.0, max_digits=12),
        ),
    ]
