# Generated by Django 4.2.17 on 2026-03-14 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0007_systemconfiguration_default_hourly_rate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemconfiguration',
            name='app_update_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='systemconfiguration',
            name='force_update',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='systemconfiguration',
            name='min_android_version',
            field=models.CharField(default='1.0.0', max_length=20),
        ),
        migrations.AddField(
            model_name='systemconfiguration',
            name='min_ios_version',
            field=models.CharField(default='1.0.0', max_length=20),
        ),
    ]
