# Generated by Django 4.2.7 on 2026-09-26 19:33

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0009_consolidate_payment_config'),
    ]

    operations = [
        migrations.AddField(
            model_name='country',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='country',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='systemconfiguration',
            name='country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_related', to='common.country'),
        ),
        migrations.AddField(
            model_name='systemconfiguration',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='systemconfiguration',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='systemconfiguration',
            name='company_name',
            field=models.CharField(default='JAMBO PARK', max_length=100),
        ),
        migrations.AlterField(
            model_name='systemconfiguration',
            name='contact_email',
            field=models.EmailField(default='admin@jambopark.com', max_length=254),
        ),
        migrations.AlterField(
            model_name='systemconfiguration',
            name='contact_phone',
            field=models.CharField(default='+256000000000', max_length=20),
        ),
        migrations.AlterField(
            model_name='systemconfiguration',
            name='timezone',
            field=models.CharField(default='Africa/Kampala', max_length=50),
        ),
    ]
