# Generated by Django 4.2.11 on 2026-02-13 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rewards', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='loyaltyaccount',
            index=models.Index(fields=['user'], name='rwd_loy_usr_idx'),
        ),
        migrations.AddIndex(
            model_name='loyaltyaccount',
            index=models.Index(fields=['tier'], name='rwd_loy_tier_idx'),
        ),
        migrations.AddIndex(
            model_name='pointtransaction',
            index=models.Index(fields=['account'], name='rwd_ptx_acc_idx'),
        ),
        migrations.AddIndex(
            model_name='pointtransaction',
            index=models.Index(fields=['transaction_type'], name='rwd_ptx_type_idx'),
        ),
        migrations.AddIndex(
            model_name='pointtransaction',
            index=models.Index(fields=['created_at'], name='rwd_ptx_cr_idx'),
        ),
        migrations.AddIndex(
            model_name='pointtransaction',
            index=models.Index(fields=['account', 'created_at'], name='rwd_ptx_acc_cr_idx'),
        ),
    ]
