# Generated by Django 4.2.7 on 2026-03-15 09:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('parking', '0020_zoneapplication_access_instructions_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ZoneApplicationPublic',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('application_id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Public-facing unique identifier for the application', unique=True)),
                ('applicant_name', models.CharField(max_length=100)),
                ('applicant_email', models.EmailField(max_length=254)),
                ('applicant_phone', models.CharField(max_length=30)),
                ('proposed_name', models.CharField(max_length=100)),
                ('address', models.TextField()),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('total_slots', models.IntegerField(default=1)),
                ('proposed_hourly_rate', models.DecimalField(decimal_places=2, max_digits=12)),
                ('operating_hours', models.CharField(default='24/7', help_text='E.g. 24/7, 8 AM - 6 PM', max_length=100)),
                ('parking_surface', models.CharField(choices=[('paved', 'Paved/Concrete'), ('gravel', 'Gravel/Dirt'), ('indoor', 'Indoor/Garage')], default='paved', max_length=50)),
                ('has_security', models.BooleanField(default=False)),
                ('has_cctv', models.BooleanField(default=False)),
                ('access_instructions', models.TextField(blank=True)),
                ('documents', models.FileField(blank=True, help_text='Proof of ownership or ID', null=True, upload_to='zone_applications/public/')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], db_index=True, default='pending', max_length=20)),
                ('admin_notes', models.TextField(blank=True)),
                ('created_zone', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='public_application', to='parking.zone')),
            ],
            options={
                'verbose_name': 'Zone Application',
                'verbose_name_plural': 'Zone Applications',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OwnerBankDetails',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('bank_name', models.CharField(max_length=100)),
                ('account_number', models.CharField(max_length=50)),
                ('account_holder_name', models.CharField(max_length=100)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='bank_details', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Owner Bank Details',
                'verbose_name_plural': 'Owner Bank Details',
            },
        ),
    ]
