# Generated by Django 4.2.7 on 2026-03-15 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zone_owner_portal', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='zoneapplicationpublic',
            name='demo_email',
            field=models.EmailField(blank=True, help_text='Login email sent to the applicant upon approval', max_length=254),
        ),
        migrations.AddField(
            model_name='zoneapplicationpublic',
            name='demo_password',
            field=models.CharField(blank=True, help_text='Temporary password generated upon approval — shown once, remind owner to change it', max_length=100),
        ),
    ]
