# Generated by Django 4.2.7 on 2026-03-16 08:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0019_add_zone_owner_role'),
        ('zone_owner_portal', '0002_add_demo_credentials'),
    ]

    operations = [
        migrations.CreateModel(
            name='ZoneOwner',
            fields=[
            ],
            options={
                'verbose_name': 'Zone Owner (Partner)',
                'verbose_name_plural': 'Zone Owners (Partners)',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('accounts.user',),
        ),
    ]
