# Generated by Django 4.2.7 on 2026-09-26 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zone_owner_portal', '0003_zoneowner'),
    ]

    operations = [
        migrations.AddField(
            model_name='zoneapplicationpublic',
            name='zone_picture',
            field=models.ImageField(blank=True, help_text='Photo of the actual parking zone', null=True, upload_to='zone_applications/public_pics/'),
        ),
    ]
