# Generated by Django 4.2.7 on 2026-02-14 18:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AIChatContext',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(blank=True, choices=[('START_PARKING', 'Start Parking'), ('STOP_PARKING', 'Stop Parking'), ('TOPUP_WALLET', 'Top Up Wallet')], max_length=50, null=True)),
                ('action_data', models.JSONField(blank=True, default=dict)),
                ('step', models.CharField(choices=[('IDLE', 'Idle'), ('WAITING_CONFIRMATION', 'Waiting Confirmation')], default='IDLE', max_length=50)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ai_context', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
