# Generated by Django 4.2.7 on 2026-02-14 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support_chat', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aichatcontext',
            name='step',
            field=models.CharField(choices=[('IDLE', 'Idle'), ('WAITING_CONFIRMATION', 'Waiting Confirmation'), ('WAITING_INPUT', 'Waiting Input')], default='IDLE', max_length=50),
        ),
    ]
