# Generated by Django 4.2.7 on 2026-02-07 03:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0002_alter_user_email_alter_user_first_name_and_more'),
        ('parking', '0004_zone_total_slots'),
        ('enforcement', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='violation',
            name='description',
            field=models.TextField(verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='violation',
            name='fine_amount',
            field=models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Fine Amount'),
        ),
        migrations.AlterField(
            model_name='violation',
            name='is_paid',
            field=models.BooleanField(default=False, verbose_name='Is Paid'),
        ),
        migrations.AlterField(
            model_name='violation',
            name='latitude',
            field=models.DecimalField(decimal_places=6, max_digits=9, verbose_name='Latitude'),
        ),
        migrations.AlterField(
            model_name='violation',
            name='longitude',
            field=models.DecimalField(decimal_places=6, max_digits=9, verbose_name='Longitude'),
        ),
        migrations.AlterField(
            model_name='violation',
            name='officer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='issued_violations', to=settings.AUTH_USER_MODEL, verbose_name='Officer'),
        ),
        migrations.AlterField(
            model_name='violation',
            name='paid_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Paid At'),
        ),
        migrations.AlterField(
            model_name='violation',
            name='parking_session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='violations', to='parking.parkingsession', verbose_name='Parking Session'),
        ),
        migrations.AlterField(
            model_name='violation',
            name='vehicle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='violations', to='accounts.vehicle', verbose_name='Vehicle'),
        ),
        migrations.AlterField(
            model_name='violation',
            name='violation_type',
            field=models.CharField(choices=[('expired', 'Expired Parking'), ('no_payment', 'No Payment'), ('wrong_zone', 'Wrong Zone'), ('disabled_spot', 'Disabled Spot Violation')], max_length=20, verbose_name='Violation Type'),
        ),
        migrations.AlterField(
            model_name='violation',
            name='zone',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='violations', to='parking.zone', verbose_name='Zone'),
        ),
    ]
