# Generated by Django 4.2.7 on 2026-02-11 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enforcement', '0002_alter_violation_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='violation',
            name='violation_type',
            field=models.CharField(choices=[('expired', 'Expired Parking'), ('no_payment', 'No Payment'), ('wrong_zone', 'Wrong Zone'), ('disabled_spot', 'Disabled Spot Violation'), ('overdue_parking', 'Overdue Parking')], max_length=20, verbose_name='Violation Type'),
        ),
    ]
