# Generated by Django 4.2.11 on 2026-02-11 09:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('parking', '0007_rename_parking_session_vehicle_status_idx_parking_par_vehicle_a87999_idx_and_more'),
        ('enforcement', '0003_alter_violation_violation_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='OfficerStatus',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_online', models.BooleanField(default=False)),
                ('went_online_at', models.DateTimeField(blank=True, null=True)),
                ('went_offline_at', models.DateTimeField(blank=True, null=True)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
            ],
            options={
                'verbose_name': 'Officer Status',
                'verbose_name_plural': 'Officer Statuses',
            },
        ),
        migrations.CreateModel(
            name='QRCodeScan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('qr_data', models.TextField(verbose_name='QR Data')),
                ('scan_status', models.CharField(choices=[('valid', 'Valid'), ('invalid', 'Invalid'), ('expired', 'Expired'), ('already_ended', 'Already Ended')], default='valid', max_length=20, verbose_name='Scan Status')),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('session_ended', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AlterModelOptions(
            name='officerlog',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddIndex(
            model_name='officerlog',
            index=models.Index(fields=['officer', '-created_at'], name='enforcement_officer_83b125_idx'),
        ),
        migrations.AddIndex(
            model_name='officerlog',
            index=models.Index(fields=['action', '-created_at'], name='enforcement_action_e94424_idx'),
        ),
        migrations.AddField(
            model_name='qrcodescan',
            name='officer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='qr_scans', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='qrcodescan',
            name='parking_session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='qr_scans', to='parking.parkingsession', verbose_name='Parking Session'),
        ),
        migrations.AddField(
            model_name='officerstatus',
            name='current_zone',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='parking.zone'),
        ),
        migrations.AddField(
            model_name='officerstatus',
            name='officer',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='officer_status', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='qrcodescan',
            index=models.Index(fields=['officer', '-created_at'], name='enforcement_officer_1581b5_idx'),
        ),
        migrations.AddIndex(
            model_name='qrcodescan',
            index=models.Index(fields=['parking_session', '-created_at'], name='enforcement_parking_7950df_idx'),
        ),
    ]
