# Generated by Django 4.2.11 on 2026-02-11 16:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('enforcement', '0005_add_violation_indexes'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='violation',
            name='violation_vehicle_paid_idx',
        ),
        migrations.RemoveIndex(
            model_name='violation',
            name='violation_zone_paidat_idx',
        ),
    ]
