# Generated by Django 4.2.11 on 2026-02-11 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enforcement', '0006_remove_violation_violation_vehicle_paid_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='violation',
            name='is_paid',
            field=models.BooleanField(db_index=True, default=False, verbose_name='Is Paid'),
        ),
        migrations.AlterField(
            model_name='violation',
            name='violation_type',
            field=models.CharField(choices=[('expired', 'Expired Parking'), ('no_payment', 'No Payment'), ('wrong_zone', 'Wrong Zone'), ('disabled_spot', 'Disabled Spot Violation'), ('overdue_parking', 'Overdue Parking')], db_index=True, max_length=20, verbose_name='Violation Type'),
        ),
    ]
