# Generated by Django 4.2.11 on 2026-02-13 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enforcement', '0007_alter_violation_is_paid_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='officerlog',
            index=models.Index(fields=['created_at'], name='enf_log_cr_idx'),
        ),
        migrations.AddIndex(
            model_name='officerstatus',
            index=models.Index(fields=['is_online'], name='enf_stat_online_idx'),
        ),
        migrations.AddIndex(
            model_name='officerstatus',
            index=models.Index(fields=['current_zone'], name='enf_stat_zone_idx'),
        ),
        migrations.AddIndex(
            model_name='qrcodescan',
            index=models.Index(fields=['officer'], name='enf_qrcodescan_officer_idx'),
        ),
        migrations.AddIndex(
            model_name='qrcodescan',
            index=models.Index(fields=['parking_session'], name='enf_qrcodescan_session_idx'),
        ),
        migrations.AddIndex(
            model_name='qrcodescan',
            index=models.Index(fields=['created_at'], name='enf_qrcodescan_created_at_idx'),
        ),
        migrations.AddIndex(
            model_name='violation',
            index=models.Index(fields=['vehicle'], name='enf_violation_vehicle_idx'),
        ),
        migrations.AddIndex(
            model_name='violation',
            index=models.Index(fields=['officer'], name='enf_violation_officer_idx'),
        ),
        migrations.AddIndex(
            model_name='violation',
            index=models.Index(fields=['zone'], name='enf_violation_zone_idx'),
        ),
        migrations.AddIndex(
            model_name='violation',
            index=models.Index(fields=['created_at'], name='enf_violation_created_at_idx'),
        ),
        migrations.AddIndex(
            model_name='violation',
            index=models.Index(fields=['officer', 'created_at'], name='enf_viol_off_cr_idx'),
        ),
        migrations.AddIndex(
            model_name='violation',
            index=models.Index(fields=['is_paid', 'created_at'], name='enf_viol_paid_cr_idx'),
        ),
        migrations.AddIndex(
            model_name='violation',
            index=models.Index(fields=['violation_type'], name='enf_violation_type_idx'),
        ),
    ]
