# Generated by Django 4.2.7 on 2026-02-18 11:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0006_countryconfig'),
        ('enforcement', '0008_officerlog_enf_log_cr_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='violation',
            name='country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_related', to='common.country'),
        ),
    ]
