# Generated by Django 4.2.7 on 2026-03-31 06:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0023_zoneapplication_zone_picture'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('common', '0008_systemconfiguration_app_update_url_and_more'),
        ('payments', '0011_wallettransaction_closing_balance_and_more'),
        ('enforcement', '0009_violation_country'),
    ]

    operations = [
        migrations.CreateModel(
            name='GuestParkingSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('license_plate', models.CharField(db_index=True, max_length=20, verbose_name='License Plate')),
                ('driver_name', models.CharField(max_length=100, verbose_name='Driver Name')),
                ('driver_phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Driver Phone')),
                ('start_time', models.DateTimeField(db_index=True, verbose_name='Start Time')),
                ('planned_end_time', models.DateTimeField(verbose_name='Planned End Time')),
                ('actual_end_time', models.DateTimeField(blank=True, null=True, verbose_name='Actual End Time')),
                ('estimated_cost', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Estimated Cost')),
                ('final_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Final Cost')),
                ('payment_status', models.CharField(choices=[('pending', 'Pending Payment'), ('completed', 'Payment Completed'), ('failed', 'Payment Failed'), ('free', 'Free Session')], db_index=True, default='pending', max_length=20, verbose_name='Payment Status')),
                ('status', models.CharField(choices=[('active', 'Active'), ('ended', 'Ended'), ('overdue', 'Overdue'), ('cancelled', 'Cancelled')], db_index=True, default='active', max_length=20, verbose_name='Status')),
                ('notes', models.TextField(blank=True, verbose_name='Officer Notes')),
                ('country', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_related', to='common.country')),
                ('officer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_guest_sessions', to=settings.AUTH_USER_MODEL, verbose_name='Officer')),
                ('parking_slot', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='parking.parkingslot', verbose_name='Parking Slot')),
                ('payment_transaction', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='guest_parking_session', to='payments.transaction', verbose_name='Payment Transaction')),
                ('zone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guest_sessions', to='parking.zone', verbose_name='Zone')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['license_plate'], name='enf_guest_plate_idx'), models.Index(fields=['officer', '-created_at'], name='enf_guest_off_cr_idx'), models.Index(fields=['zone', '-created_at'], name='enf_guest_zone_cr_idx'), models.Index(fields=['status'], name='enf_guest_status_idx'), models.Index(fields=['payment_status'], name='enf_guest_pay_idx'), models.Index(fields=['start_time'], name='enf_guest_start_idx'), models.Index(fields=['planned_end_time'], name='enf_guest_end_idx')],
            },
        ),
    ]
