# Generated by Django 4.2.7 on 2026-09-26 19:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0010_country_latitude_country_longitude_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('enforcement', '0010_guestparkingsession'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guestparkingsession',
            name='country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_related', to='common.country'),
        ),
        migrations.AlterField(
            model_name='violation',
            name='country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_related', to='common.country'),
        ),
        migrations.AlterField(
            model_name='violation',
            name='officer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='issued_violations', to=settings.AUTH_USER_MODEL, verbose_name='Officer'),
        ),
    ]
