# Generated by Django 4.2.11 on 2026-02-11 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='revenuerecord',
            name='date',
            field=models.DateField(db_index=True),
        ),
    ]
