import { createContext, useContext, useState, useEffect } from 'react';

// Simple translation system
const TRANSLATIONS = {
  en: {
    dashboard: 'Dashboard',
    'welcome-message': 'Welcome back! Here\'s how your space is performing.',
    'total-earnings': 'Total Earnings',
    'all-time': 'All time',
    'this-month': 'This Month',
    'current-month': 'Current month',
    'today-earnings': 'Today',
    'today-s-earnings': 'Today\'s earnings',
    'active-sessions': 'Active Sessions',
    'reservations': 'Reservations',
    'pending': 'pending',
    'earnings-last-30-days': 'Earnings — Last 30 Days',
    'no-earnings-data': 'No earnings data yet.',
    'revenue-split-by-zone': 'Revenue Split by Zone',
    'portfolio-analytics': 'Portfolio Analytics',
    'sessions-30d': 'Sessions (30d)',
    'total-sessions': 'Total sessions',
    'avg-session-duration': 'Avg Session Duration',
    'average-duration': 'Average duration',
    'avg-revenue-session': 'Avg Revenue/Session',
    'per-session': 'Per session',
    'occupancy-trends': 'Occupancy Trends (Last 7 Days)',
    'peak-hours-analysis': 'Peak Hours Analysis',
    'zone-performance-comparison': 'Zone Performance Comparison',
    'revenue-30d': 'Revenue (30d)',
    'sessions-30d': 'Sessions (30d)',
    'avg-occupancy': 'Avg Occupancy',
    'utilization-rate': 'Utilization',
    'hourly-rate': 'Hourly Rate',
    'dynamic-pricing': 'Dynamic Pricing',
    'reservations-enabled': 'Reservations',
    'yes': 'Yes',
    'no': 'No',
    'revenue-optimization-suggestions': 'Revenue Optimization Suggestions',
    'your-zones': 'Your Zones',
    'zone': 'Zone',
    'slots': 'Slots',
    'occupancy': 'Occupancy',
    'recent-sessions': 'Recent Sessions',
    'vehicle': 'Vehicle',
    'start-time': 'Start Time',
    'status': 'Status',
    'amount': 'Amount',
    'recent-reservations': 'Recent Reservations',
    'user': 'User',
    'planned-start': 'Planned Start',
    'fee-deducted': 'Fee Deducted',
    'manage-zones': 'Manage Zones',
    'pricing-rules': 'Pricing Rules',
    'add-new-zone': 'Add New Zone',
    'edit': 'Edit',
    'pricing': 'Pricing',
    'back-to-dashboard': 'Back to Dashboard',
    'save-changes': 'Save Changes',
    'saving': 'Saving...',
    'basic-information': 'Basic Information',
    'zone-name': 'Zone Name',
    'zone-code': 'Zone Code',
    'description': 'Description',
    'describe-zone': 'Describe your parking zone',
    'pricing-settings': 'Pricing Settings',
    'base-hourly-rate': 'Base Hourly Rate',
    'max-duration-hours': 'Max Duration (hours)',
    'commission-rate': 'Commission Rate (%)',
    'enable-dynamic-pricing': 'Enable Dynamic Pricing',
    'dynamic-pricing-description': 'Allow automatic price adjustments based on time, demand, or special events',
    'enable-reservations': 'Enable Reservations',
    'reservations-description': 'Allow users to reserve parking spots in advance',
    'capacity-location': 'Capacity & Location',
    'total-slots': 'Total Slots',
    'latitude': 'Latitude',
    'longitude': 'Longitude',
    'radius-meters': 'Radius (meters)',
    'images-diagrams': 'Images & Diagrams',
    'zone-photo-url': 'Zone Photo URL',
    'layout-diagram-url': 'Layout Diagram URL',
    'diagram-width': 'Diagram Width (px)',
    'diagram-height': 'Diagram Height (px)',
    'status-analytics': 'Status & Analytics',
    'current-occupancy': 'Current Occupancy',
    'active-rules': 'Active Rules',
    'zone-active': 'Zone is Active',
    'zone-active-description': 'Inactive zones won\'t be visible to users',
    'no-zones-yet': 'No zones yet',
    'create-first-zone': 'Create your first parking zone to get started.',
    'create-first-rule': 'Create your first pricing rule to optimize revenue.',
    'dynamic-pricing-disabled': 'Dynamic pricing is disabled for this zone',
    'enable-in-settings': 'Enable dynamic pricing in zone settings to create pricing rules.',
    'no-rules-yet': 'No pricing rules yet',
    'manage-rules': 'Manage Rules',
    'time-based': 'Time Based',
    'demand-based': 'Demand Based',
    'special-event': 'Special Event',
    'priority': 'Priority',
    'rate': 'Rate',
    'active': 'Active',
    'inactive': 'Inactive',
    'disable': 'Disable',
    'enable': 'Enable',
    'delete': 'Delete',
    'create-rule': 'Create Rule',
    'edit-rule': 'Edit Rule',
    'cancel': 'Cancel',
    'save': 'Save',
    'time': 'Time',
    'days': 'Days',
    'all-days': 'All days',
    'occupancy-threshold': 'Occupancy',
    'greater-equal': '≥',
    'less-equal': '≤',
    'period': 'Period',
    'english': 'English',
    'spanish': 'Español',
    'french': 'Français',
    'german': 'Deutsch',
    'italian': 'Italiano',
    'portuguese': 'Português',
    'dutch': 'Nederlands',
    'swedish': 'Svenska',
    'danish': 'Dansk',
    'norwegian': 'Norsk',
    'finnish': 'Suomi',
    'dark-theme': 'Dark Theme',
    'light-theme': 'Light Theme',
    nav: {
      dashboard: 'Dashboard',
      addZone: 'Add New Zone',
      manageZones: 'Manage Zones',
      pricingRules: 'Pricing Rules',
      bankDetails: 'Bank Details',
      changePassword: 'Change Password'
    },
    theme: {
      darkMode: 'Dark Mode',
      lightMode: 'Light Mode'
    },
    auth: {
      signOut: 'Sign Out'
    },
    landing: {
      howItWorks: 'How It Works',
      benefits: 'Benefits',
      getTheApp: 'Get the App',
      checkStatus: 'Check Status',
      partnerLogin: 'Partner Login',
      earnPassiveIncome: 'Earn passive income from your parking space',
      smartParking: 'Smart Parking Management',
      smartParkingDesc: 'Transform your parking spaces into revenue-generating assets with our intelligent management platform.',
      getStarted: 'Get Started',
      learnMore: 'Learn More',
      turnSpaceIntoIncome: 'Turn Your Space Into',
      realIncome: 'Real Income',
      heroSubtitle: 'List your parking space on Space Park and earn money every time someone parks. Real-time analytics, automatic payouts, and total control — all in your partner dashboard.',
      applyNow: 'Apply Now — Free',
      learnHowItWorks: 'Learn How It Works'
    }
  },
  es: {
    dashboard: 'Panel de Control',
    'welcome-message': '¡Bienvenido de vuelta! Aquí está el rendimiento de tu espacio.',
    'total-earnings': 'Ganancias Totales',
    'all-time': 'Todo el tiempo',
    'this-month': 'Este Mes',
    'current-month': 'Mes actual',
    'today-earnings': 'Hoy',
    'today-s-earnings': 'Ganancias de hoy',
    'active-sessions': 'Sesiones Activas',
    'reservations': 'Reservas',
    'pending': 'pendiente',
    'earnings-last-30-days': 'Ganancias — Últimos 30 días',
    'no-earnings-data': 'Aún no hay datos de ganancias.',
    'revenue-split-by-zone': 'Distribución de Ingresos por Zona',
    'portfolio-analytics': 'Análisis de Portafolio',
    'sessions-30d': 'Sesiones (30d)',
    'total-sessions': 'Sesiones totales',
    'avg-session-duration': 'Duración Promedio de Sesión',
    'average-duration': 'Duración promedio',
    'avg-revenue-session': 'Ingreso Promedio/Sesión',
    'per-session': 'Por sesión',
    'occupancy-trends': 'Tendencias de Ocupación (Últimos 7 días)',
    'peak-hours-analysis': 'Análisis de Horas Pico',
    'zone-performance-comparison': 'Comparación de Rendimiento por Zona',
    'revenue-30d': 'Ingresos (30d)',
    'sessions-30d': 'Sesiones (30d)',
    'avg-occupancy': 'Ocupación Promedio',
    'utilization-rate': 'Utilización',
    'hourly-rate': 'Tarifa por Hora',
    'dynamic-pricing': 'Precios Dinámicos',
    'reservations-enabled': 'Reservas',
    'yes': 'Sí',
    'no': 'No',
    'revenue-optimization-suggestions': 'Sugerencias de Optimización de Ingresos',
    'your-zones': 'Tus Zonas',
    'zone': 'Zona',
    'slots': 'Espacios',
    'occupancy': 'Ocupación',
    'recent-sessions': 'Sesiones Recientes',
    'vehicle': 'Vehículo',
    'start-time': 'Hora de Inicio',
    'status': 'Estado',
    'amount': 'Monto',
    'recent-reservations': 'Reservas Recientes',
    'user': 'Usuario',
    'planned-start': 'Inicio Planificado',
    'fee-deducted': 'Tarifa Deducida',
    'manage-zones': 'Administrar Zonas',
    'pricing-rules': 'Reglas de Precios',
    'add-new-zone': 'Agregar Nueva Zona',
    'edit': 'Editar',
    'pricing': 'Precios',
    'back-to-dashboard': 'Volver al Panel',
    'save-changes': 'Guardar Cambios',
    'saving': 'Guardando...',
    'basic-information': 'Información Básica',
    'zone-name': 'Nombre de Zona',
    'zone-code': 'Código de Zona',
    'description': 'Descripción',
    'describe-zone': 'Describe tu zona de estacionamiento',
    'pricing-settings': 'Configuración de Precios',
    'base-hourly-rate': 'Tarifa Base por Hora',
    'max-duration-hours': 'Duración Máxima (horas)',
    'commission-rate': 'Tasa de Comisión (%)',
    'enable-dynamic-pricing': 'Habilitar Precios Dinámicos',
    'dynamic-pricing-description': 'Permitir ajustes automáticos de precios basados en tiempo, demanda o eventos especiales',
    'enable-reservations': 'Habilitar Reservas',
    'reservations-description': 'Permitir a los usuarios reservar espacios de estacionamiento con anticipación',
    'capacity-location': 'Capacidad y Ubicación',
    'total-slots': 'Espacios Totales',
    'latitude': 'Latitud',
    'longitude': 'Longitud',
    'radius-meters': 'Radio (metros)',
    'images-diagrams': 'Imágenes y Diagramas',
    'zone-photo-url': 'URL de Foto de Zona',
    'layout-diagram-url': 'URL de Diagrama de Diseño',
    'diagram-width': 'Ancho del Diagrama (px)',
    'diagram-height': 'Altura del Diagrama (px)',
    'status-analytics': 'Estado y Análisis',
    'current-occupancy': 'Ocupación Actual',
    'active-rules': 'Reglas Activas',
    'zone-active': 'Zona está Activa',
    'zone-active-description': 'Las zonas inactivas no serán visibles para los usuarios',
    'no-zones-yet': 'Aún no hay zonas',
    'create-first-zone': 'Crea tu primera zona de estacionamiento para comenzar.',
    'create-first-rule': 'Crea tu primera regla de precios para optimizar ingresos.',
    'dynamic-pricing-disabled': 'Los precios dinámicos están deshabilitados para esta zona',
    'enable-in-settings': 'Habilita los precios dinámicos en la configuración de zona para crear reglas de precios.',
    'no-rules-yet': 'Aún no hay reglas de precios',
    'manage-rules': 'Administrar Reglas',
    'time-based': 'Basado en Tiempo',
    'demand-based': 'Basado en Demanda',
    'special-event': 'Evento Especial',
    'priority': 'Prioridad',
    'rate': 'Tarifa',
    'active': 'Activo',
    'inactive': 'Inactivo',
    'disable': 'Deshabilitar',
    'enable': 'Habilitar',
    'delete': 'Eliminar',
    'create-rule': 'Crear Regla',
    'edit-rule': 'Editar Regla',
    'cancel': 'Cancelar',
    'save': 'Guardar',
    'time': 'Tiempo',
    'days': 'Días',
    'all-days': 'Todos los días',
    'occupancy-threshold': 'Ocupación',
    'greater-equal': '≥',
    'less-equal': '≤',
    'period': 'Período',
    'english': 'English',
    'spanish': 'Español',
    'french': 'Français',
    'german': 'Deutsch',
    'italian': 'Italiano',
    'portuguese': 'Português',
    'dutch': 'Nederlands',
    'swedish': 'Svenska',
    'danish': 'Dansk',
    'norwegian': 'Norsk',
    'finnish': 'Suomi',
    'dark-theme': 'Tema Oscuro',
    'light-theme': 'Tema Claro',
    nav: {
      dashboard: 'Panel de Control',
      addZone: 'Agregar Nueva Zona',
      manageZones: 'Administrar Zonas',
      pricingRules: 'Reglas de Precios',
      bankDetails: 'Detalles Bancarios',
      changePassword: 'Cambiar Contraseña'
    },
    theme: {
      darkMode: 'Modo Oscuro',
      lightMode: 'Modo Claro'
    },
    auth: {
      signOut: 'Cerrar Sesión'
    },
    landing: {
      howItWorks: 'Cómo Funciona',
      benefits: 'Beneficios',
      getTheApp: 'Obtener la App',
      checkStatus: 'Verificar Estado',
      partnerLogin: 'Acceso de Socio',
      earnPassiveIncome: 'Gana ingresos pasivos de tu espacio de estacionamiento',
      smartParking: 'Gestión Inteligente de Estacionamiento',
      smartParkingDesc: 'Transforma tus espacios de estacionamiento en activos generadores de ingresos con nuestra plataforma de gestión inteligente.',
      getStarted: 'Comenzar',
      learnMore: 'Saber Más',
      turnSpaceIntoIncome: 'Convierte Tu Espacio en',
      realIncome: 'Ingresos Reales',
      heroSubtitle: 'Lista tu espacio de estacionamiento en Space Park y gana dinero cada vez que alguien estaciona. Análisis en tiempo real, pagos automáticos y control total — todo en tu panel de socio.',
      applyNow: 'Aplicar Ahora — Gratis',
      learnHowItWorks: 'Aprende Cómo Funciona'
    }
  }
  // Add more languages as needed
};

const LanguageContext = createContext(null);

export function LanguageProvider({ children }) {
  const [language, setLanguage] = useState(localStorage.getItem('language') || 'en');

  useEffect(() => {
    localStorage.setItem('language', language);
  }, [language]);

  const t = (key) => {
    const keys = key.split('.');
    let value = TRANSLATIONS[language];
    
    for (const k of keys) {
      value = value?.[k];
    }
    
    if (value !== undefined) return value;
    
    // Fallback to English
    value = TRANSLATIONS.en;
    for (const k of keys) {
      value = value?.[k];
    }
    
    return value !== undefined ? value : key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
}