name: Flutter CI

on:
  push:
    branches: [ "main", "develop" ]
  pull_request:
    branches: [ "main", "develop" ]

jobs:
  analyze_and_test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Flutter
      uses: subosito/flutter-action@v2
      with:
        channel: 'stable'
        
    - name: Get dependencies (User App)
      working-directory: ./parking_user_app
      run: flutter pub get
      
    - name: Analyze (User App)
      working-directory: ./parking_user_app
      run: flutter analyze
      
    - name: Run Tests (User App)
      working-directory: ./parking_user_app
      run: flutter test

    - name: Get dependencies (Officer App)
      working-directory: ./parking_officer_app
      run: flutter pub get
      
    - name: Analyze (Officer App)
      working-directory: ./parking_officer_app
      run: flutter analyze
      
    - name: Run Tests (Officer App)
      working-directory: ./parking_officer_app
      run: flutter test
