# Generated by Django 4.2.7 on 2026-02-07 03:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0004_zone_total_slots'),
        ('payments', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notificationevent',
            options={'ordering': ['-created_at'], 'verbose_name': 'Notification Event', 'verbose_name_plural': 'Notification Events'},
        ),
        migrations.RemoveField(
            model_name='notificationevent',
            name='event_type',
        ),
        migrations.RemoveField(
            model_name='notificationevent',
            name='parking_session',
        ),
        migrations.RemoveField(
            model_name='notificationevent',
            name='transaction',
        ),
        migrations.AddField(
            model_name='notificationevent',
            name='category',
            field=models.CharField(choices=[('parking', 'Parking'), ('violations', 'Violations'), ('payments', 'Payments'), ('reservations', 'Reservations'), ('system', 'System'), ('promo', 'Promotions')], default='system', max_length=20),
        ),
        migrations.AddField(
            model_name='notificationevent',
            name='metadata',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='notificationevent',
            name='type',
            field=models.CharField(choices=[('parking_ended', 'Parking Ended'), ('violation_received', 'Violation Received'), ('payment_successful', 'Payment Successful'), ('payment_failed', 'Payment Failed'), ('reservation_confirmed', 'Reservation Confirmed'), ('reservation_cancelled', 'Reservation Cancelled'), ('maintenance_alert', 'Maintenance Alert'), ('system_alert', 'System Alert'), ('promotional_offer', 'Promotional Offer'), ('other', 'Other')], default='other', max_length=50),
        ),
        migrations.CreateModel(
            name='UserPreferences',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('language', models.CharField(choices=[('en', 'English'), ('fr', 'Français'), ('es', 'Español'), ('pt', 'Português'), ('sw', 'Swahili'), ('am', 'አማርኛ'), ('ar', 'العربية'), ('de', 'Deutsch')], default='en', max_length=5)),
                ('currency', models.CharField(choices=[('USD', 'US Dollar'), ('EUR', 'Euro'), ('GBP', 'British Pound'), ('ZAR', 'South African Rand'), ('NGN', 'Nigerian Naira'), ('KES', 'Kenyan Shilling'), ('GHS', 'Ghanaian Cedi'), ('EGP', 'Egyptian Pound')], default='USD', max_length=3)),
                ('enable_parking_notifications', models.BooleanField(default=True)),
                ('enable_violation_notifications', models.BooleanField(default=True)),
                ('enable_payment_notifications', models.BooleanField(default=True)),
                ('enable_promotional_notifications', models.BooleanField(default=True)),
                ('enable_push_notifications', models.BooleanField(default=True)),
                ('enable_sms_notifications', models.BooleanField(default=False)),
                ('enable_email_notifications', models.BooleanField(default=True)),
                ('theme_mode', models.CharField(choices=[('light', 'Light'), ('dark', 'Dark'), ('auto', 'Auto')], default='auto', max_length=10)),
                ('font_size', models.CharField(choices=[('small', 'Small'), ('normal', 'Normal'), ('large', 'Large')], default='normal', max_length=10)),
                ('biometric_enabled', models.BooleanField(default=False)),
                ('two_factor_enabled', models.BooleanField(default=False)),
                ('parking_session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='parking.parkingsession')),
                ('transaction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='payments.transaction')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='preferences', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Preference',
                'verbose_name_plural': 'User Preferences',
            },
        ),
    ]
