# Generated by Django 4.2.11 on 2026-02-10 08:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('notifications', '0004_alter_userpreferences_currency'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='chatconversation',
            new_name='notificatio_user_id_042c0e_idx',
            old_name='notifications_user_id_status_idx',
        ),
        migrations.RenameIndex(
            model_name='chatconversation',
            new_name='notificatio_status_d33ef1_idx',
            old_name='notifications_status_created_idx',
        ),
        migrations.RenameIndex(
            model_name='chatmessage',
            new_name='notificatio_convers_2203f4_idx',
            old_name='notifications_conv_created_idx',
        ),
        migrations.RenameIndex(
            model_name='chatmessage',
            new_name='notificatio_is_read_87a0ac_idx',
            old_name='notifications_is_read_sender_idx',
        ),
        migrations.RemoveField(
            model_name='userpreferences',
            name='parking_session',
        ),
        migrations.RemoveField(
            model_name='userpreferences',
            name='transaction',
        ),
        migrations.AlterField(
            model_name='chatconversation',
            name='assigned_agent',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'support_agent'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_conversations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='chatconversation',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='chatmessage',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
