# Generated by Django 4.2.11 on 2026-02-11 16:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0006_add_notification_indexes'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='notificationevent',
            name='notification_user_read_created_idx',
        ),
        migrations.RemoveIndex(
            model_name='notificationevent',
            name='notification_metadata_gin',
        ),
    ]
