# Generated by Django 4.2.11 on 2026-02-11 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0007_remove_notificationevent_notification_user_read_created_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificationevent',
            name='is_read',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
