# Generated by Django 4.2.11 on 2026-02-12 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0008_alter_notificationevent_is_read'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificationevent',
            name='push_error',
            field=models.TextField(blank=True, help_text='Error message if push notification failed', null=True),
        ),
        migrations.AddField(
            model_name='notificationevent',
            name='push_sent_at',
            field=models.DateTimeField(blank=True, help_text='When push notification was sent', null=True),
        ),
        migrations.AddField(
            model_name='notificationevent',
            name='sent_via_push',
            field=models.BooleanField(default=False, help_text='Whether push notification was sent via FCM'),
        ),
    ]
