# Generated by Django 4.2.11 on 2026-02-12 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0009_notificationevent_push_error_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificationevent',
            name='is_promotional',
            field=models.BooleanField(default=False, help_text='Mark as promotional content'),
        ),
        migrations.AddField(
            model_name='notificationevent',
            name='priority',
            field=models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='medium', help_text='Priority level for custom notifications', max_length=10),
        ),
        migrations.AddField(
            model_name='notificationevent',
            name='show_as_dialog',
            field=models.BooleanField(default=False, help_text='Show as in-app dialog when user opens app'),
        ),
        migrations.AlterField(
            model_name='notificationevent',
            name='type',
            field=models.CharField(choices=[('parking_ended', 'Parking Ended'), ('violation_received', 'Violation Received'), ('payment_successful', 'Payment Successful'), ('payment_failed', 'Payment Failed'), ('reservation_confirmed', 'Reservation Confirmed'), ('reservation_cancelled', 'Reservation Cancelled'), ('maintenance_alert', 'Maintenance Alert'), ('system_alert', 'System Alert'), ('promotional_offer', 'Promotional Offer'), ('custom_admin', 'Custom Admin'), ('other', 'Other')], default='other', max_length=50),
        ),
    ]
