# Generated by Django 4.2.7 on 2026-02-13 13:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('notifications', '0010_notificationevent_is_promotional_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatconversation',
            name='assigned_agent',
            field=models.ForeignKey(blank=True, limit_choices_to=models.Q(('role', 'support_agent'), models.Q(('can_receive_chats', True), ('role', 'officer')), _connector='OR'), null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_conversations', to=settings.AUTH_USER_MODEL),
        ),
    ]
