# Generated by Django 4.2.11 on 2026-02-13 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0011_alter_chatconversation_assigned_agent'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='notificationevent',
            index=models.Index(fields=['user'], name='ntf_evt_usr_idx'),
        ),
        migrations.AddIndex(
            model_name='notificationevent',
            index=models.Index(fields=['type'], name='ntf_evt_type_idx'),
        ),
        migrations.AddIndex(
            model_name='notificationevent',
            index=models.Index(fields=['category'], name='ntf_evt_cat_idx'),
        ),
        migrations.AddIndex(
            model_name='notificationevent',
            index=models.Index(fields=['created_at'], name='ntf_evt_cr_idx'),
        ),
        migrations.AddIndex(
            model_name='notificationevent',
            index=models.Index(fields=['user', 'is_read'], name='ntf_evt_usr_rd_idx'),
        ),
        migrations.AddIndex(
            model_name='notificationevent',
            index=models.Index(fields=['user', 'created_at'], name='ntf_evt_usr_cr_idx'),
        ),
        migrations.AddIndex(
            model_name='userpreferences',
            index=models.Index(fields=['user'], name='ntf_pref_usr_idx'),
        ),
    ]
