# Generated by Django 4.2.7 on 2026-09-26 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0012_notificationevent_ntf_evt_usr_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificationevent',
            name='type',
            field=models.CharField(choices=[('parking_ended', 'Parking Ended'), ('violation_received', 'Violation Received'), ('payment_successful', 'Payment Successful'), ('payment_failed', 'Payment Failed'), ('reservation_confirmed', 'Reservation Confirmed'), ('reservation_cancelled', 'Reservation Cancelled'), ('reservation_reminder', 'Reservation Reminder'), ('country_welcome', 'Country Welcome'), ('country_alert', 'Country Alert'), ('maintenance_alert', 'Maintenance Alert'), ('system_alert', 'System Alert'), ('promotional_offer', 'Promotional Offer'), ('custom_admin', 'Custom Admin'), ('other', 'Other')], default='other', max_length=50),
        ),
    ]
